function showSummary(summaryToShow) {

    var summaries = {"eragon": "When Eragon finds a polished blue stone in the forest, he thinks it is the lucky discovery of a poor farm boy; perhaps it will buy his family meat for the winter. But when the stone brings a dragon hatchling, Eragon realizes he has stumbled upon a legacy nearly as old as the Empire itself. Overnight his simple life is shattered, and he is thrust into a perilous new world of destiny, magic, and power. With only an ancient sword and the advice of an old storyteller for guidance, Eragon and the fledgling dragon must navigate the dangerous terrain and dark enemies of an Empire ruled by a king whose evil knows no bounds. Can Eragon take up the mantle of the legendary Dragon Riders? The fate of the Empire may rest in his hands."};

    summaries["daughter"] = "Sorcha is the seventh child and only daughter of Lord Colum of Sevenwaters. Bereft of a mother, she is comforted by her six brothers who love and protect her. Sorcha is the light in their lives, they are determined that she know only contentment. But Sorcha's joy is shattered when her father is bewitched by his new wife, an evil enchantress who binds her brothers with a terrible spell, a spell which only Sorcha can lift-by staying silent. If she speaks before she completes the quest set to her by the Fair Folk and their queen, the Lady of the Forest, she will lose her brothers forever.";
    summaries["bookthief"] = "Trying to make sense of the horrors of World War II, Death relates the story of Liesel--a young German girl whose book-stealing and story-telling talents help sustain her family and the Jewish man they are hiding, as well as their neighbors.";
    summaries["spiritedaway"] = "10-year-old Chihiro and her parents stumble upon a seemingly abandoned amusement park. After her mother and father are turned into giant pigs, Chihiro meets the mysterious Haku, who explains that the park is a resort for supernatural beings who need a break from their time spent in the earthly realm, and that she must work there to free herself and her parents.";
    summaries["interstellar"] = "In Earth's future, a global crop blight and second Dust Bowl are slowly rendering the planet uninhabitable. Professor Brand, a brilliant NASA physicist, is working on plans to save mankind by transporting Earth's population to a new home via a wormhole. But first, Brand must send former NASA pilot Cooper and a team of researchers through the wormhole and across the galaxy to find out which of three planets could be mankind's new home.";
    summaries["dragon"] = "In the midst of her wedding ceremony, princess Miroslava is kidnapped by a dragon and carried away to a remote island. Mira left everything behind - family, friends and groom. Now the only things she has are a stone cage and a mysterious young man named Arman. But who is he and what is he doing on that island?";
    summaries["avatar"] = "In a world where humans can bend the four elements, water, earth, fire, and air, the ruthless Fire Nation has engaged the rest of the world in a war that has lasted one hundred years. The only one who could stop them was the Avatar, master all four elements, but when the world needed him most, he vanished. A hundred years passed and the new Avatar, a young Airbender named Aang, has been found. Now it's up to him and his friends to defeat the Fire Nation and bring balance back to the world.";
    summaries["sherlock"] = "A modernised series of adaptations of the Sherlock Holmes novels by Sir Arthur Conan Doyle. John Watson, an army doctor, is wounded in Afghanistan and discharged from the Army. Back in London his search for a place to stay leads him to share a flat with Sherlock Holmes, a brilliant but eccentric private detective. Together they solve baffling, and often bizarre, murder mysteries and compete with Holmes' nemesis, the criminal genius Moriarty.";
    summaries["amazingrace"] = "THE AMAZING RACE is a multi-Emmy Award-winning reality series hosted by Emmy Award-nominated host Phil Keoghan. Each season, teams embark on a trek around the world. At every destination, each team must compete in a series of challenges, some mental and some physical, and only when the tasks are completed will they learn of their next desination. Teams who are the farthest behind are gradually eliminated as the contest progresses, and first team to arrive at the final destination wins THE AMAZING RACE and the $1 million prize.";
    summaries["botw"] = "An entry in the longrunning The Legend of Zelda series, Breath of the Wild takes place at the end of the Zelda timeline; the player controls Link, who awakens from a hundred-year slumber to defeat Calamity Ganon before it can destroy the kingdom of Hyrule. Similarly to the original Legend of Zelda (1986), players are given little instruction and can explore the open world freely. Tasks include collecting multipurpose items to aid in objectives or solving puzzles and side quests for rewards. Breath of the Wild's world is unstructured and designed to reward experimentation, and the story can be completed in a nonlinear fashion."
    summaries["smgalaxy"] = "Super Mario Galaxy is set in outer space, where Mario travels through different galaxies to collect Power Stars, earned by completing missions, defeating bosses, or reaching a particular area. Each galaxy contains planetoids and orbiting structures for the player to explore, and each astronomical object has its own gravitational force, allowing the player to completely circumnavigate the planetoids, walking sideways or upside down."
    summaries["stardew"] = "You’ve inherited your grandfather’s old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home? It won’t be easy. Ever since Joja Corporation came to town, the old ways of life have all but disappeared. But the valley seems full of opportunity. With a little dedication, you might just be the one to restore Stardew Valley to greatness!";

    var titles = {"eragon": "Eragon by Christopher Paolini", "daughter": "Daughter of the Forest by Juliet Marillier", "bookthief": "The Book Thief by Markus Zusak", "spiritedaway": "Spirited Away", "dragon": "I Am Dragon", "interstellar": "Interstellar", "sherlock": "Sherlock", "avatar": "Avatar: The Last Airbender", "amazingrace": "The Amazing Race",
    "amazingrace": "The Amazing Race", "botw": "The Legend of Zelda: Breath of the Wild", "smgalaxy": "Super Mario Galaxy", "stardew": "Stardew Valley"}

    var rec = document.getElementById("summary");
    var title = document.getElementById("recTitle");

    if (rec.style.display === "none" || rec.style.display === "" || title.innerHTML !== titles[summaryToShow]) {
        rec.innerHTML = summaries[summaryToShow];
        title.innerHTML = titles[summaryToShow];
        rec.style.display = "block";
        title.style.display = "block";
    }
    else {
        rec.style.display = "none";
        title.style.display = "none";
    }
}
